# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user1 = User.create(email: 'k@k',             password: '1234', password_confirmation: '1234', fname: 'Ken',   lname: 'Guie',    username: 'Ken')
user2 = User.create(email: 'keika@gmail.com', password: '1234', password_confirmation: '1234', fname: 'Keika', lname: 'Jones', username: 'Keika')
user3 = User.create(email: 'jyim@gmail.com',  password: '1234', password_confirmation: '1234', fname: 'Jason', lname: 'Yim',   username: 'Jason')
 
emotion1 = Emotion.create(name: 'happy')
emotion2 = Emotion.create(name: 'sad')
emotion3 = Emotion.create(name: 'angry')
emotion4 = Emotion.create(name: 'calm')
 
# Happy Colors #

# reds #
color1 = Color.create(name: 'red', hexcode: '#ED4652')
color2 = Color.create(name: 'maroon', hexcode: '#C32148')
color42 = Color.create(name: 'vermillion red', hexcode: '#E94840')

# oranges #
color3 = Color.create(name: 'burnt orange', hexcode: '#FF7034')
color4 = Color.create(name: 'vivid tangerine', hexcode: '#FF9980')
color5 = Color.create(name: 'neon carrot', hexcode: '#FF9933')

# yellows #
color6 = Color.create(name: 'beach sand yellow', hexcode: '#FFFF99')
color7 = Color.create(name: 'unmellow yellow', hexcode: '#FFFF66')
color8 = Color.create(name: 'golden yellow', hexcode: '#FFDF00')

# greens #
color9 = Color.create(name: 'yellow green', hexcode: '#47C43F')
color10 = Color.create(name: 'emerald', hexcode: '#00C957')
color11 = Color.create(name: 'blue green', hexcode: '#2AC4AB')
color12 = Color.create(name: 'seafoam green', hexcode: '#71EEB8')
color41 = Color.create(name: 'bamboo green', hexcode: '#2A9C7A')

# blues #
color13 = Color.create(name: 'electric blue', hexcode: '#23B2EE')
color14 = Color.create(name: 'sky blue', hexcode: '#76D7EA')
color15 = Color.create(name: 'blue', hexcode: '#265AFF')
color16 = Color.create(name: 'metallic seaweed', hexcode: '#28A0BB')
color17 = Color.create(name: 'baby blue', hexcode: '#A3E0FF')

# pinks #
color18 = Color.create(name: 'primrose', hexcode: '#FF93BE')
color19 = Color.create(name: 'piggy pink', hexcode: '#FDD7E4')
color20 = Color.create(name: 'fluorescent pink', hexcode: '#FF5AAC')

# purples #
color21 = Color.create(name: 'lavender', hexcode: '#D6AEDD')
color22 = Color.create(name: 'vivid violet', hexcode: '#803790')
color23 = Color.create(name: 'petite rose', hexcode: '#A4509B')

# Happy ColorEmotions #
colorEmotion1 = ColorEmotion.create(emotion_id: 1, color_id: 1)
colorEmotion2 = ColorEmotion.create(emotion_id: 1, color_id: 2)
colorEmotion3 = ColorEmotion.create(emotion_id: 1, color_id: 3)
colorEmotion4 = ColorEmotion.create(emotion_id: 1, color_id: 4)
colorEmotion5 = ColorEmotion.create(emotion_id: 1, color_id: 5)
colorEmotion6 = ColorEmotion.create(emotion_id: 1, color_id: 6)
colorEmotion7 = ColorEmotion.create(emotion_id: 1, color_id: 7)
colorEmotion8 = ColorEmotion.create(emotion_id: 1, color_id: 8)
colorEmotion9 = ColorEmotion.create(emotion_id: 1, color_id: 9)
colorEmotion10 = ColorEmotion.create(emotion_id: 1, color_id: 10)
colorEmotion11 = ColorEmotion.create(emotion_id: 1, color_id: 11)
colorEmotion12 = ColorEmotion.create(emotion_id: 1, color_id: 12)
colorEmotion13 = ColorEmotion.create(emotion_id: 1, color_id: 13)
colorEmotion14 = ColorEmotion.create(emotion_id: 1, color_id: 14)
colorEmotion15 = ColorEmotion.create(emotion_id: 1, color_id: 15)
colorEmotion16 = ColorEmotion.create(emotion_id: 1, color_id: 16)
colorEmotion17 = ColorEmotion.create(emotion_id: 1, color_id: 17)
colorEmotion18 = ColorEmotion.create(emotion_id: 1, color_id: 18)
colorEmotion19 = ColorEmotion.create(emotion_id: 1, color_id: 19)
colorEmotion20 = ColorEmotion.create(emotion_id: 1, color_id: 20)
colorEmotion21 = ColorEmotion.create(emotion_id: 1, color_id: 21)
colorEmotion22 = ColorEmotion.create(emotion_id: 1, color_id: 22)
colorEmotion23 = ColorEmotion.create(emotion_id: 1, color_id: 23)
colorEmotion41 = ColorEmotion.create(emotion_id: 1, color_id: 41)
colorEmotion42 = ColorEmotion.create(emotion_id: 1, color_id: 42)

# Sad Colors #

# greys #
color24 = Color.create(name: 'silver', hexcode: '#C9C0BB')
color25 = Color.create(name: 'slate', hexcode: '#404E5A')
color26 = Color.create(name: 'grey', hexcode: '#8B8680')
color27 = Color.create(name: 'crystal', hexcode: '#D5D5D5')

# blues #

color28 = Color.create(name: 'pastel blue', hexcode: '#80CEE1')
color29 = Color.create(name: 'wild blue yonder', hexcode: '#7A89B8')
color30 = Color.create(name: 'denim', hexcode: '#1560BD')

# browns #
color31 = Color.create(name: 'tumbleweed', hexcode: '#DEA681')
color32 = Color.create(name: 'tawny', hexcode: '#997C52')
color33 = Color.create(name: 'beaver', hexcode: '#926F5B')

# greens #
color34 = Color.create(name: 'forest green', hexcode: '#5FA777')
color35 = Color.create(name: 'pea green', hexcode: '#739122')
color36 = Color.create(name: 'asparagus', hexcode: '#7BA05B')

# oranges #
color36 = Color.create(name: 'tiger orange', hexcode: '#CB7119')
color37 = Color.create(name: 'metallic sunburst', hexcode: '#EDD63D')

# reds #
color38 = Color.create(name: 'gel fx rose', hexcode: '#A9473A')
color39 = Color.create(name: 'shimmering blush', hexcode: '#E69296')
color40 = Color.create(name: 'christmas red', hexcode: '#B22222')

# Sad ColorEmotions #
colorEmotion24 = ColorEmotion.create(emotion_id: 2, color_id: 24)
colorEmotion25 = ColorEmotion.create(emotion_id: 2, color_id: 25)
colorEmotion26 = ColorEmotion.create(emotion_id: 2, color_id: 26)
colorEmotion27 = ColorEmotion.create(emotion_id: 2, color_id: 27)
colorEmotion28 = ColorEmotion.create(emotion_id: 2, color_id: 28)
colorEmotion29 = ColorEmotion.create(emotion_id: 2, color_id: 29)
colorEmotion30 = ColorEmotion.create(emotion_id: 2, color_id: 30)
colorEmotion31 = ColorEmotion.create(emotion_id: 2, color_id: 31)
colorEmotion32 = ColorEmotion.create(emotion_id: 2, color_id: 32)
colorEmotion33 = ColorEmotion.create(emotion_id: 2, color_id: 33)
colorEmotion34 = ColorEmotion.create(emotion_id: 2, color_id: 34)
colorEmotion35 = ColorEmotion.create(emotion_id: 2, color_id: 35) 
colorEmotion36 = ColorEmotion.create(emotion_id: 2, color_id: 36)
colorEmotion37 = ColorEmotion.create(emotion_id: 2, color_id: 37)
colorEmotion38 = ColorEmotion.create(emotion_id: 2, color_id: 38)
colorEmotion39 = ColorEmotion.create(emotion_id: 2, color_id: 39)
colorEmotion40 = ColorEmotion.create(emotion_id: 2, color_id: 40)

# angry colors #

color41 = Color.create(name: 'maroon', hexcode: '#C32148')
color42 = Color.create(name: 'vivid tangerine', hexcode: '#FF9980')
color43 = Color.create(name: 'unmellow yellow', hexcode: '#FFFF66')
color44 = Color.create(name: 'emerald', hexcode: '#00C957')
color45 = Color.create(name: 'metallic seaweed', hexcode: '#28A0BB')
color46 = Color.create(name: 'vivid violet', hexcode: '#803790')
color47 = Color.create(name: 'denim', hexcode: '#1560BD')
color48 = Color.create(name: 'gel fx rose', hexcode: '#A9473A')
color49 = Color.create(name: 'forest green', hexcode: '#5FA777')
color50 = Color.create(name: 'christmas red', hexcode: '#B22222')
color51 = Color.create(name: 'metallic sunburst', hexcode: '#EDD63D')
color52 = Color.create(name: 'tiger orange', hexcode: '#CB7119')

colorEmotion41 = ColorEmotion.create(emotion_id: 3, color_id: 41)
colorEmotion42 = ColorEmotion.create(emotion_id: 3, color_id: 42)
colorEmotion43 = ColorEmotion.create(emotion_id: 3, color_id: 43)
colorEmotion44 = ColorEmotion.create(emotion_id: 3, color_id: 44)
colorEmotion45 = ColorEmotion.create(emotion_id: 3, color_id: 45)
colorEmotion46 = ColorEmotion.create(emotion_id: 3, color_id: 46)
colorEmotion47 = ColorEmotion.create(emotion_id: 3, color_id: 47)
colorEmotion48 = ColorEmotion.create(emotion_id: 3, color_id: 48)
colorEmotion49 = ColorEmotion.create(emotion_id: 3, color_id: 49)
colorEmotion50 = ColorEmotion.create(emotion_id: 3, color_id: 50)
colorEmotion51 = ColorEmotion.create(emotion_id: 3, color_id: 51)
colorEmotion52 = ColorEmotion.create(emotion_id: 3, color_id: 52)

#calm colors

color53 = Color.create(name: 'foam green', hexcode: '#9FD8C7')
color54 = Color.create(name: 'steel grey', hexcode: '#D2D2D2')
color55 = Color.create(name: 'salmon', hexcode: '#FC7B7B')
color56 = Color.create(name: 'rust', hexcode: '#C3A26F')
color57 = Color.create(name: 'forest green', hexcode: '#418910')
color58 = Color.create(name: 'teal', hexcode: '#60B8C8')
color59 = Color.create(name: 'silver', hexcode: '#C9C0BB')
color60 = Color.create(name: 'shimmering blush', hexcode: '#E69296')

colorEmotion53 = ColorEmotion.create(emotion_id: 4, color_id: 53)
colorEmotion54 = ColorEmotion.create(emotion_id: 4, color_id: 54)
colorEmotion55 = ColorEmotion.create(emotion_id: 4, color_id: 55)
colorEmotion56 = ColorEmotion.create(emotion_id: 4, color_id: 56)
colorEmotion57 = ColorEmotion.create(emotion_id: 4, color_id: 57)
colorEmotion58 = ColorEmotion.create(emotion_id: 4, color_id: 58)
colorEmotion59 = ColorEmotion.create(emotion_id: 4, color_id: 59)
colorEmotion60 = ColorEmotion.create(emotion_id: 4, color_id: 60)

# Happy Images #

image1  = Image.create(name: 'are-you-happy', 		file: "https://s3.amazonaws.com/emotionsproject/happy/are-you-happy.jpg")
image2  = Image.create(name: 'be-happy', 					file: "https://s3.amazonaws.com/emotionsproject/happy/be_happy-wallpaper.jpg")
image3  = Image.create(name: 'because-im-happy', 	file: "https://s3.amazonaws.com/emotionsproject/happy/because-im-happy.jpg")
image4  = Image.create(name: 'birthday=mouse', 		file: "https://s3.amazonaws.com/emotionsproject/happy/birthday-mouse.jpg")
image5  = Image.create(name: 'cat-glasses', 			file: "https://s3.amazonaws.com/emotionsproject/happy/cat-glasses.jpg")
image6  = Image.create(name: 'cereal-smiley', 		file: "https://s3.amazonaws.com/emotionsproject/happy/cereal-smiley.jpg")
image7  = Image.create(name: 'chamomile', 				file: "https://s3.amazonaws.com/emotionsproject/happy/chamomile.jpg")
image8  = Image.create(name: 'color-run', 				file: "https://s3.amazonaws.com/emotionsproject/happy/color-run.jpg")
image9  = Image.create(name: 'finger-friends', 		file: "https://s3.amazonaws.com/emotionsproject/happy/finger-friends.jpg")
image10 = Image.create(name: 'funny-kitten', 			file: "https://s3.amazonaws.com/emotionsproject/happy/funny-kitten.jpg")
image11 = Image.create(name: 'happy-1', 					file: "https://s3.amazonaws.com/emotionsproject/happy/happy-1.jpg")
image12 = Image.create(name: 'happy-baby', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-baby.jpg")
image13 = Image.create(name: 'happy-cat', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-cat.jpg")
image14 = Image.create(name: 'happy-child', 			file: "https://s3.amazonaws.com/emotionsproject/happy/happy-child.jpg")
image15 = Image.create(name: 'happy-dog', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-dog.jpg")
image16 = Image.create(name: 'happy-family', 			file: "https://s3.amazonaws.com/emotionsproject/happy/happy-family.jpg")
image17 = Image.create(name: 'happy-feet', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-feet.jpg")
image18 = Image.create(name: 'happy-love', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-love.jpg")
image19 = Image.create(name: 'happy-smiley', 			file: "https://s3.amazonaws.com/emotionsproject/happy/happy-smiley.jpg")
image20 = Image.create(name: 'happy-sun', 				file: "https://s3.amazonaws.com/emotionsproject/happy/happy-sun.jpg")
image21 = Image.create(name: 'like-a-child', 			file: "https://s3.amazonaws.com/emotionsproject/happy/like-a-child.jpg")
image22 = Image.create(name: 'married-barefoot',	file: "https://s3.amazonaws.com/emotionsproject/happy/married-barefoot.jpg")
image23 = Image.create(name: 'minions', 					file: "https://s3.amazonaws.com/emotionsproject/happy/minions.jpg")
image24 = Image.create(name: 'pink-smiley', 			file: "https://s3.amazonaws.com/emotionsproject/happy/pink-smiley.jpg")
image25 = Image.create(name: 'winter-happiness', 	file: "https://s3.amazonaws.com/emotionsproject/happy/winter-happiness.jpg")

# Happy ImageEmotions #

imageEmotion1  = ImageEmotion.create(image_id: 1,  emotion_id: 1)
imageEmotion2  = ImageEmotion.create(image_id: 2,  emotion_id: 1)
imageEmotion3  = ImageEmotion.create(image_id: 3,  emotion_id: 1)
imageEmotion4  = ImageEmotion.create(image_id: 4,  emotion_id: 1)
imageEmotion5  = ImageEmotion.create(image_id: 5,  emotion_id: 1)
imageEmotion6  = ImageEmotion.create(image_id: 6,  emotion_id: 1)
imageEmotion7  = ImageEmotion.create(image_id: 7,  emotion_id: 1)
imageEmotion8  = ImageEmotion.create(image_id: 8,  emotion_id: 1)
imageEmotion9  = ImageEmotion.create(image_id: 9,  emotion_id: 1)
imageEmotion10 = ImageEmotion.create(image_id: 10, emotion_id: 1)
imageEmotion11 = ImageEmotion.create(image_id: 11, emotion_id: 1)
imageEmotion12 = ImageEmotion.create(image_id: 12, emotion_id: 1)
imageEmotion13 = ImageEmotion.create(image_id: 13, emotion_id: 1)
imageEmotion14 = ImageEmotion.create(image_id: 14, emotion_id: 1)
imageEmotion15 = ImageEmotion.create(image_id: 15, emotion_id: 1)
imageEmotion16 = ImageEmotion.create(image_id: 16, emotion_id: 1)
imageEmotion17 = ImageEmotion.create(image_id: 17, emotion_id: 1)
imageEmotion18 = ImageEmotion.create(image_id: 18, emotion_id: 1)
imageEmotion19 = ImageEmotion.create(image_id: 19, emotion_id: 1)
imageEmotion20 = ImageEmotion.create(image_id: 20, emotion_id: 1)
imageEmotion21 = ImageEmotion.create(image_id: 21, emotion_id: 1)
imageEmotion22 = ImageEmotion.create(image_id: 22, emotion_id: 1)
imageEmotion23 = ImageEmotion.create(image_id: 23, emotion_id: 1)
imageEmotion24 = ImageEmotion.create(image_id: 24, emotion_id: 1)
imageEmotion25 = ImageEmotion.create(image_id: 25, emotion_id: 1)


# Sad Images #

image26 = Image.create(name: 'balloon', 					file: "https://s3.amazonaws.com/emotionsproject/sad/balloon.jpg")
image27 = Image.create(name: 'bird-rain', 				file: "https://s3.amazonaws.com/emotionsproject/sad/bird-in-rain.jpg")
image28 = Image.create(name: 'elephant', 					file: "https://s3.amazonaws.com/emotionsproject/sad/elephant.jpg")
image29 = Image.create(name: 'foggy-day', 				file: "https://s3.amazonaws.com/emotionsproject/sad/foggy-day.jpg")
image30 = Image.create(name: 'girl-rain', 				file: "https://s3.amazonaws.com/emotionsproject/sad/girl-rain.jpg")
image31 = Image.create(name: 'lonely-corner', 		file: "https://s3.amazonaws.com/emotionsproject/sad/lonely-corner.jpg")
image32 = Image.create(name: 'main-rain', 				file: "https://s3.amazonaws.com/emotionsproject/sad/man-rain.jpg")
image33 = Image.create(name: 'moments', 					file: "https://s3.amazonaws.com/emotionsproject/sad/moments.jpg")
image34 = Image.create(name: 'puppy-eyes', 				file: "https://s3.amazonaws.com/emotionsproject/sad/puppy-eyes.jpg")
image35 = Image.create(name: 'sad-angel', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-angel.jpg")
image36 = Image.create(name: 'sad-boy-clown', 		file: "https://s3.amazonaws.com/emotionsproject/sad/sad-boy-clown.jpg")
image37 = Image.create(name: 'sad-cat', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-cat.jpg")
image38 = Image.create(name: 'sad-chibi', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-chibi.jpg")
image39 = Image.create(name: 'sad-child', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-child.jpg")
image40 = Image.create(name: 'sad-danbo', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-danbo.jpg")
image41 = Image.create(name: 'sad-dog', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-dog.jpg")
image42 = Image.create(name: 'sad-kitty', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-kitty.jpg")
image43 = Image.create(name: 'sad-rain', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-rain.jpg")
image44 = Image.create(name: 'sad-robot', 				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-robot.jpg")
image45 = Image.create(name: 'sad-sketch',				file: "https://s3.amazonaws.com/emotionsproject/sad/sad-sketch.jpg")
image46 = Image.create(name: 'sad-tree', 					file: "https://s3.amazonaws.com/emotionsproject/sad/sad-tree.jpg")
image47 = Image.create(name: 'tear', 							file: "https://s3.amazonaws.com/emotionsproject/sad/tear.jpg")

# Sad ImageEmotions #

imageEmotion26 = ImageEmotion.create(image_id: 26, emotion_id: 2)
imageEmotion27 = ImageEmotion.create(image_id: 27, emotion_id: 2)
imageEmotion28 = ImageEmotion.create(image_id: 28, emotion_id: 2)
imageEmotion29 = ImageEmotion.create(image_id: 29, emotion_id: 2)
imageEmotion30 = ImageEmotion.create(image_id: 30, emotion_id: 2)
imageEmotion31 = ImageEmotion.create(image_id: 31, emotion_id: 2)
imageEmotion32 = ImageEmotion.create(image_id: 32, emotion_id: 2)
imageEmotion33 = ImageEmotion.create(image_id: 33, emotion_id: 2)
imageEmotion34 = ImageEmotion.create(image_id: 34, emotion_id: 2)
imageEmotion35 = ImageEmotion.create(image_id: 35, emotion_id: 2)
imageEmotion36 = ImageEmotion.create(image_id: 36, emotion_id: 2)
imageEmotion37 = ImageEmotion.create(image_id: 37, emotion_id: 2)
imageEmotion38 = ImageEmotion.create(image_id: 38, emotion_id: 2)
imageEmotion39 = ImageEmotion.create(image_id: 39, emotion_id: 2)
imageEmotion40 = ImageEmotion.create(image_id: 40, emotion_id: 2)
imageEmotion41 = ImageEmotion.create(image_id: 41, emotion_id: 2)
imageEmotion42 = ImageEmotion.create(image_id: 42, emotion_id: 2)
imageEmotion43 = ImageEmotion.create(image_id: 43, emotion_id: 2)
imageEmotion44 = ImageEmotion.create(image_id: 44, emotion_id: 2)
imageEmotion45 = ImageEmotion.create(image_id: 45, emotion_id: 2)
imageEmotion46 = ImageEmotion.create(image_id: 46, emotion_id: 2)
imageEmotion47 = ImageEmotion.create(image_id: 47, emotion_id: 2)


# Angry Images #

image48 = Image.create(name: 'building explosion',    file: 'https://s3.amazonaws.com/emotionsproject/angry/building-explosion.jpg')
image49 = Image.create(name: 'car crash',             file: 'https://s3.amazonaws.com/emotionsproject/angry/car-crash.jpg')
image50 = Image.create(name: 'eye of sauron',         file: 'https://s3.amazonaws.com/emotionsproject/angry/eye-of-sauron.jpg')
image51 = Image.create(name: 'godzilla',              file: 'https://s3.amazonaws.com/emotionsproject/angry/godzilla.jpg')
image52 = Image.create(name: 'goku',                  file: 'https://s3.amazonaws.com/emotionsproject/angry/goku.jpg')
image53 = Image.create(name: 'hulk',                  file: 'https://s3.amazonaws.com/emotionsproject/angry/hulk.jpg')
image54 = Image.create(name: 'painting1',             file: 'https://s3.amazonaws.com/emotionsproject/angry/painting1.jpg')
image55 = Image.create(name: 'painting2',             file: 'https://s3.amazonaws.com/emotionsproject/angry/painting2.jpg')
image56 = Image.create(name: 'pollock1',              file: 'https://s3.amazonaws.com/emotionsproject/angry/pollock1.jpg')
image57 = Image.create(name: 'pollock2',              file: 'https://s3.amazonaws.com/emotionsproject/angry/pollock2.jpg')
image58 = Image.create(name: 'purple lightning',      file: 'https://s3.amazonaws.com/emotionsproject/angry/purple-lightning.jpg')
image59 = Image.create(name: 'riot',                  file: 'https://s3.amazonaws.com/emotionsproject/angry/riot.jpg')
image60 = Image.create(name: 'tornade1',              file: 'https://s3.amazonaws.com/emotionsproject/angry/tornado1.jpg')
image61 = Image.create(name: 'tornado2',              file: 'https://s3.amazonaws.com/emotionsproject/angry/tornado2.jpg')
image62 = Image.create(name: 'videogame',             file: 'https://s3.amazonaws.com/emotionsproject/angry/videogame.jpg')
image63 = Image.create(name: 'volcano and lightning', file: 'https://s3.amazonaws.com/emotionsproject/angry/volcano-lightning.jpg')
image64 = Image.create(name: 'volcano',               file: 'https://s3.amazonaws.com/emotionsproject/angry/volcano.jpg')
image65 = Image.create(name: 'waves', 		            file: 'https://s3.amazonaws.com/emotionsproject/angry/waves.jpg')
image66 = Image.create(name: "Angry Batman", file: "https://s3.amazonaws.com/emotionsproject/angry/angry-batman.jpg")
image67 = Image.create(name: "Angry Tiger", file: "https://s3.amazonaws.com/emotionsproject/angry/angry-tiger.jpg")
image68 = Image.create(name: "Bombing Darwin", file: "https://s3.amazonaws.com/emotionsproject/angry/bombing-darwin.jpg")
image69 = Image.create(name: "Deadly Bombing", file: "https://s3.amazonaws.com/emotionsproject/angry/deadly-bombing.jpg")
image70 = Image.create(name: "Gorilla", file: "https://s3.amazonaws.com/emotionsproject/angry/gorilla.jpg")
image71 = Image.create(name: "Green Anaconda", file: "https://s3.amazonaws.com/emotionsproject/angry/green-anaconda.jpg")
image72 = Image.create(name: "Hatred Eyes", file: "https://s3.amazonaws.com/emotionsproject/angry/hatred-eyes.jpg")
image73 = Image.create(name: "Heavy Metal", file: "https://s3.amazonaws.com/emotionsproject/angry/heavy-metal.jpg")
image74 = Image.create(name: "Heavey Metal2", file: "https://s3.amazonaws.com/emotionsproject/angry/heavy-metal2.jpg")
image75 = Image.create(name: "I Hate You", file: "https://s3.amazonaws.com/emotionsproject/angry/i-hate-you.jpg")
image76 = Image.create(name: "Rage Teeth", file: "https://s3.amazonaws.com/emotionsproject/angry/rage-teeth.jpg")

# Angry ImageEmotion #

imageEmotion48 = ImageEmotion.create(emotion_id: 3, image_id: 48)
imageEmotion49 = ImageEmotion.create(emotion_id: 3, image_id: 49)
imageEmotion50 = ImageEmotion.create(emotion_id: 3, image_id: 50)
imageEmotion51 = ImageEmotion.create(emotion_id: 3, image_id: 51)
imageEmotion52 = ImageEmotion.create(emotion_id: 3, image_id: 52)
imageEmotion53 = ImageEmotion.create(emotion_id: 3, image_id: 53)
imageEmotion54 = ImageEmotion.create(emotion_id: 3, image_id: 54)
imageEmotion55 = ImageEmotion.create(emotion_id: 3, image_id: 55)
imageEmotion56 = ImageEmotion.create(emotion_id: 3, image_id: 56)
imageEmotion57 = ImageEmotion.create(emotion_id: 3, image_id: 57)
imageEmotion58 = ImageEmotion.create(emotion_id: 3, image_id: 58)
imageEmotion59 = ImageEmotion.create(emotion_id: 3, image_id: 59)
imageEmotion60 = ImageEmotion.create(emotion_id: 3, image_id: 60)
imageEmotion61 = ImageEmotion.create(emotion_id: 3, image_id: 61)
imageEmotion62 = ImageEmotion.create(emotion_id: 3, image_id: 62)
imageEmotion63 = ImageEmotion.create(emotion_id: 3, image_id: 63)
imageEmotion64 = ImageEmotion.create(emotion_id: 3, image_id: 64)
imageEmotion65 = ImageEmotion.create(emotion_id: 3, image_id: 65)
imageEmotion66 = ImageEmotion.create(emotion_id: 3, image_id: 66)
imageEmotion67 = ImageEmotion.create(emotion_id: 3, image_id: 67)
imageEmotion68 = ImageEmotion.create(emotion_id: 3, image_id: 68)
imageEmotion69 = ImageEmotion.create(emotion_id: 3, image_id: 69)
imageEmotion70 = ImageEmotion.create(emotion_id: 3, image_id: 70)
imageEmotion71 = ImageEmotion.create(emotion_id: 3, image_id: 71)
imageEmotion72 = ImageEmotion.create(emotion_id: 3, image_id: 72)
imageEmotion73 = ImageEmotion.create(emotion_id: 3, image_id: 73)
imageEmotion74 = ImageEmotion.create(emotion_id: 3, image_id: 74)
imageEmotion75 = ImageEmotion.create(emotion_id: 3, image_id: 75)
imageEmotion76 = ImageEmotion.create(emotion_id: 3, image_id: 76)


# calm images #

image77 = Image.create(name: "Avatar Flowers", file: "https://s3.amazonaws.com/emotionsproject/calm/avatar-flowers.jpg")
image78 = Image.create(name: "Bed of Leaves", file: "https://s3.amazonaws.com/emotionsproject/calm/bed-of-leaves.jpg")
image79 = Image.create(name: "Blue Pond", file: "https://s3.amazonaws.com/emotionsproject/calm/blue-pond.jpg")
image80 = Image.create(name: "Bonsai", file: "https://s3.amazonaws.com/emotionsproject/calm/bonsai.jpg")
image81 = Image.create(name: "Bridge", file: "https://s3.amazonaws.com/emotionsproject/calm/bridge.jpg")
image82 = Image.create(name: "Buddhism", file: "https://s3.amazonaws.com/emotionsproject/calm/buddhism-symbol.jpg")
image83 = Image.create(name: "Calm Morning", file: "https://s3.amazonaws.com/emotionsproject/calm/calm-morning.jpg")
image84 = Image.create(name: "Calm Wallpaper", file: "https://s3.amazonaws.com/emotionsproject/calm/calm-wallpaper.jpg")
image85 = Image.create(name: "Calm Waves", file: "https://s3.amazonaws.com/emotionsproject/calm/calm-waves.jpg")
image86 = Image.create(name: "Calmity Retro", file: "https://s3.amazonaws.com/emotionsproject/calm/calmity-retro.jpg")
image87 = Image.create(name: "Cello", file: "https://s3.amazonaws.com/emotionsproject/calm/cello.jpg")
image88 = Image.create(name: "Rhine River", file: "https://s3.amazonaws.com/emotionsproject/calm/crooked-rhine-river.jpg")
image89 = Image.create(name: "Evening Lake", file: "https://s3.amazonaws.com/emotionsproject/calm/evening-lake.jpg")
image90 = Image.create(name: "Flower Closeup", file: "https://s3.amazonaws.com/emotionsproject/calm/flower-closeup.jpg")
image91 = Image.create(name: "Girl in Garden", file: "https://s3.amazonaws.com/emotionsproject/calm/girl-garden.jpg")
image92 = Image.create(name: "Keep Calm", file: "https://s3.amazonaws.com/emotionsproject/calm/keep-calm.jpg")
image93 = Image.create(name: "Lakebed", file: "https://s3.amazonaws.com/emotionsproject/calm/lakebed.jpg")
image94 = Image.create(name: "Leaf", file: "https://s3.amazonaws.com/emotionsproject/calm/leaf.jpg")
image95 = Image.create(name: "Mountains Reflecting", file: "https://s3.amazonaws.com/emotionsproject/calm/mountains-reflecting.jpg")
image96 = Image.create(name: "Outdoor Bedroom", file: "https://s3.amazonaws.com/emotionsproject/calm/outdoor-bedroom.jpg")
image97 = Image.create(name: "Paper Flowers", file: "https://s3.amazonaws.com/emotionsproject/calm/paper-flowers.jpg")
image98 = Image.create(name: "Peace of Mind", file: "https://s3.amazonaws.com/emotionsproject/calm/peace-of-mind.jpg")
image99 = Image.create(name: "Spring Sunset", file: "https://s3.amazonaws.com/emotionsproject/calm/spring-sunset.jpg")
image100 = Image.create(name: "Sunset", file: "https://s3.amazonaws.com/emotionsproject/calm/sunset.jpg")


# Calm imageEmotions #

imageEmotion77 = ImageEmotion.create(image_id: 77, emotion_id: 4)
imageEmotion78 = ImageEmotion.create(image_id: 78, emotion_id: 4)
imageEmotion79 = ImageEmotion.create(image_id: 79, emotion_id: 4)
imageEmotion80 = ImageEmotion.create(image_id: 80, emotion_id: 4)
imageEmotion81 = ImageEmotion.create(image_id: 81, emotion_id: 4)
imageEmotion82 = ImageEmotion.create(image_id: 82, emotion_id: 4)
imageEmotion83 = ImageEmotion.create(image_id: 83, emotion_id: 4)
imageEmotion84 = ImageEmotion.create(image_id: 84, emotion_id: 4)
imageEmotion85 = ImageEmotion.create(image_id: 85, emotion_id: 4)
imageEmotion86 = ImageEmotion.create(image_id: 86, emotion_id: 4)
imageEmotion87 = ImageEmotion.create(image_id: 87, emotion_id: 4)
imageEmotion88 = ImageEmotion.create(image_id: 88, emotion_id: 4)
imageEmotion89 = ImageEmotion.create(image_id: 89, emotion_id: 4)
imageEmotion90 = ImageEmotion.create(image_id: 90, emotion_id: 4)
imageEmotion91 = ImageEmotion.create(image_id: 91, emotion_id: 4)
imageEmotion92 = ImageEmotion.create(image_id: 92, emotion_id: 4)
imageEmotion93 = ImageEmotion.create(image_id: 93, emotion_id: 4)
imageEmotion94 = ImageEmotion.create(image_id: 94, emotion_id: 4)
imageEmotion95 = ImageEmotion.create(image_id: 95, emotion_id: 4)
imageEmotion96 = ImageEmotion.create(image_id: 96, emotion_id: 4)
imageEmotion97 = ImageEmotion.create(image_id: 97, emotion_id: 4)
imageEmotion98 = ImageEmotion.create(image_id: 98, emotion_id: 4)
imageEmotion99 = ImageEmotion.create(image_id: 99, emotion_id: 4)
imageEmotion100 = ImageEmotion.create(image_id: 100, emotion_id: 4)

# Happy Music #

music1 = Music.create(name: 'Happy by Pharrell Williams', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Happy.mp3")
music2 = Music.create(name: 'The Man by Aloe Blacc', 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/The+Man.mp3")
music3 = Music.create(name: 'Fascination by Alphabeat', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Fascination.mp3")
music4 = Music.create(name: 'Chewing Gum by Annie',	 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Chewing+Gum.mp3")
music5 = Music.create(name: 'Happy Together by The Turtles', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Happy+Together.mp3")
music6 = Music.create(name: 'Dont Worry, Be Happy by Bobby McFerrin', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Don%27t+Worry%2C+Be+Happy.mp3")
music7 = Music.create(name: 'Happy Days by Pratt & McClain', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Happy+Days+(Theme+from+Happy+Days).mp3")
music8 = Music.create(name: 'Wake Me Up Before You Go Go by Wham!', 														file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Wake+Me+Up+Before+You+Go-Go.mp3")
music9 = Music.create(name: 'Walking On Sunshine by Katrina & The Waves', 											file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Walking+On+Sunshine.mp3")
music10 = Music.create(name: 'And We Danced by Macklemore', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/And+We+Danced+(feat.+Ziggy+Stardust).mp3")
music11 = Music.create(name: 'Marry You by Bruno Mars', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/06+Marry+You.mp3")
music12 = Music.create(name: 'One Week by Barenaked Ladies', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+One+Week.mp3")
music13 = Music.create(name: 'Best Day of My Life by American Authors', 												file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Best+Day+of+My+Life.mp3")
music14 = Music.create(name: 'Love On Top by Beyonce', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Love+On+Top.mp3")
music15 = Music.create(name: 'I Will Never Let You Down by Rita Ora', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/I+Will+Never+Let+You+Down.mp3")
music16 = Music.create(name: 'Mr. Blue Sky by Electric Light Orchestra', 												file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Mr.+Blue+Sky.mp3")
music17 = Music.create(name: 'My Girl by The Temptations', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/My+Girl.mp3")
music18 = Music.create(name: 'Steal My Sunshine by LEN', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Steal+My+Sunshine.mp3")
music19 = Music.create(name: 'Shake It Off by Taylor Swift', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Shake+It+Off.mp3")
music20 = Music.create(name: 'Dance Apocalyptic by Janelle Monae', 															file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Dance+Apocalyptic.mp3")
music21 = Music.create(name: 'Carried Away by Passion Pit', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Carried+Away.mp3")
music22 = Music.create(name: 'Good Luck by Basement Jaxx', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Good+Luck+(feat.+Lisa+Kekaula).mp3")
music23 = Music.create(name: 'Flaws by Bastille', 																							file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Flaws.mp3")
music24 = Music.create(name: 'I Gotta Feeling by Black Eyed Peas', 															file: "https://s3.amazonaws.com/emotionsproject/happy+songs/I+Gotta+Feeling.mp3")
music25 = Music.create(name: 'I Wanna Get Better by Bleachers', 																file: "https://s3.amazonaws.com/emotionsproject/happy+songs/I+Wanna+Get+Better.mp3")
music26 = Music.create(name: 'Hey Leonardo (She Likes Me For Me) by Bless Union Of Souls', 			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Hey+Leonardo+(She+Likes+Me+for+Me).mp3")
music27 = Music.create(name: 'Run Around by Blues Traveler', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Run+Around.mp3")
music28 = Music.create(name: 'Summer by Calvin Harris', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Summer.mp3")
music29 = Music.create(name: 'Fuck You by Cee Lo Green', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Fuck+You.mp3")
music30 = Music.create(name: 'I Belong In Your Arms by Chairlift', 															file: "https://s3.amazonaws.com/emotionsproject/happy+songs/I+Belong+in+Your+Arms.mp3")
music31 = Music.create(name: 'Boom Clap by Charli XCX', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Boom+Clap.mp3")
music32 = Music.create(name: 'Rather Be by Clean Bandit', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Rather+Be+(feat.+Jess+Glynne).mp3")
music33 = Music.create(name: 'Gold Rush by Clinton Sparks', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Gold+Rush+(feat.+2+Chainz%2C+Macklemore+%26+D.A.).mp3")
music34 = Music.create(name: 'You Make Me Feel... by Cobra Starship', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/You+Make+Me+Feel%E2%80%A6+(feat.+Sabi).mp3")
music35 = Music.create(name: 'Every Teardrop Is a Waterfall by Coldplay', 											file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Every+Teardrop+Is+a+Waterfall.mp3")
music36 = Music.create(name: 'Put Your Records On by Corinne Bailey Rae', 											file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Put+Your+Records+On.mp3")
music37 = Music.create(name: 'Accidentally In Love by Counting Crows', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Accidentally+in+Love.mp3")
music38 = Music.create(name: 'Get Lucky by Daft Punk', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Get+Lucky+(feat.+Pharrell+Williams).mp3")
music39 = Music.create(name: 'Life, Love & Laughter by Donavon Frankenreiter', 									file: "https://s3.amazonaws.com/emotionsproject/happy+songs/01+Life%2C+Love+%26+Laughter.mp3")
music40 = Music.create(name: 'Sing by Ed Sheeran', 																							file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Sing.mp3")
music41 = Music.create(name: 'Anything Could Happen by Ellie Goulding', 												file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Anything+Could+Happen.mp3")
music42 = Music.create(name: 'Dont Stop by Fleetwood Mac', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Don%27t+Stop.mp3")
music43 = Music.create(name: 'Dog Days Are Over by Florence & The Machine', 										file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Dog+Days+Are+Over.mp3")
music44 = Music.create(name: 'We Are Young by Fun.', 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/We+Are+Young+(feat.+Janelle+Mona%CC%81e).mp3")
music45 = Music.create(name: 'Best I Ever Had by Gavin DeGraw', 																file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Best+I+Ever+Had.mp3")
music46 = Music.create(name: 'Love Love Love by Hope', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Love+Love+Love+(feat.+Jason+Mraz).mp3")
music47 = Music.create(name: 'I Love It (I Dont Care) by Icona Pop', 														file: "https://s3.amazonaws.com/emotionsproject/happy+songs/I+Love+It+(I+Don%27t+Care).mp3")
music48 = Music.create(name: 'Fancy by Iggy Azalea', 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Fancy+(feat.+Charli+XCX).mp3")
music49 = Music.create(name: 'On Top of the World by Imagine Dragons', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/On+Top+of+the+World.mp3")
music50 = Music.create(name: 'Staple It Together by Jack Johnson', 															file: "https://s3.amazonaws.com/emotionsproject/happy+songs/07+Staple+It+Together.mp3")
music51 = Music.create(name: 'Geek In the Pink by Jason Mraz', 																	file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Geek+In+the+Pink.mp3")
music52 = Music.create(name: 'Bang Bang by Jessie J', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Bang+Bang+(feat.+Ariana+Grande+%26+Nicki+Minaj).mp3")
music53 = Music.create(name: 'No Such Thing by John Mayer', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/No+Such+Thing.mp3")
music54 = Music.create(name: 'Some Kind of Wonderful by Joss Stone', 														file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Some+Kind+of+Wonderful.mp3")
music55 = Music.create(name: 'Dont Stop Believin by Journey', 																	file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Don%27t+Stop+Believin%27.mp3")
music56 = Music.create(name: 'Last Friday Night by Katy Perry', 																file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Last+Friday+Night+(T.G.I.F.).mp3")
music57 = Music.create(name: 'Tralala by Kiah Victoria', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Tralala.mp3")
music58 = Music.create(name: 'Up Up & Away by Kid Cudi', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Up+Up+%26+Away.mp3")
music59 = Music.create(name: 'Hideaway by Kiesza', 																							file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Hideaway.mp3")
music60 = Music.create(name: 'Wings by Little Mix',	 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Wings.mp3")
music61 = Music.create(name: 'Daydreamin by Lupe Fiasco', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Daydreamin%27+(feat.+Jill+Scott).mp3")
music62 = Music.create(name: 'Moves Like Jagger by Maroon 5', 																	file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Moves+Like+Jagger+(feat.+Christina+Aguilera).mp3")
music63 = Music.create(name: 'All About That Bass by Meghan Trainor', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/All+About+That+Bass.mp3")
music64 = Music.create(name: 'Electric Feel by MGMT', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Electric+Feel.mp3")
music65 = Music.create(name: 'Love Never Felt So Good by Michael Jackson & Justin Timberlake', 	file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Love+Never+Felt+So+Good.mp3")
music66 = Music.create(name: 'Grace Kelly by Mika', 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Grace+Kelly.mp3")
music67 = Music.create(name: 'You Get What You Give by New Radicals', 													file: "https://s3.amazonaws.com/emotionsproject/happy+songs/You+Get+What+You+Give.mp3")
music68 = Music.create(name: 'She is Electric by Oasis', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/She%27s+Electric.mp3")
music69 = Music.create(name: 'Little Talks by Of Monsters And Men', 														file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Little+Talks.mp3")
music70 = Music.create(name: 'Live While We Are Young by One Direction', 												file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Live+While+We%27re+Young.mp3")
music71 = Music.create(name: 'Counting Stars by OneRepublic', 																	file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Counting+Stars.mp3")
music72 = Music.create(name: 'Lisztomania by Phoenix', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Lisztomania.mp3")
music73 = Music.create(name: 'King of Anything by Sara Bareilles', 															file: "https://s3.amazonaws.com/emotionsproject/happy+songs/King+of+Anything.mp3")
music74 = Music.create(name: 'Hall of Fame by The Script', 																			file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Hall+of+Fame+(feat.+will.i.am).mp3")
music75 = Music.create(name: 'Up! by Shania Twain', 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Up!.mp3")
music76 = Music.create(name: 'Closer by Tegan and Sara', 																				file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Closer.mp3")
music77 = Music.create(name: 'If Its Love by Train', 																						file: "https://s3.amazonaws.com/emotionsproject/happy+songs/If+It%27s+Love.mp3")
music78 = Music.create(name: 'Island In the Sun by Weezer', 																		file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Island+in+the+Sun.mp3")
music79 = Music.create(name: 'Bang Bang by will.i.am', 																					file: "https://s3.amazonaws.com/emotionsproject/happy+songs/Bang+Bang.mp3")

# Happy MusicEmotions #
musicEmotions1 = MusicEmotion.create(music_id: 1, emotion_id: 1)
musicEmotions2 = MusicEmotion.create(music_id: 2, emotion_id: 1)
musicEmotions3 = MusicEmotion.create(music_id: 3, emotion_id: 1)
musicEmotions4 = MusicEmotion.create(music_id: 4, emotion_id: 1)
musicEmotions5 = MusicEmotion.create(music_id: 5, emotion_id: 1)
musicEmotions6 = MusicEmotion.create(music_id: 6, emotion_id: 1)
musicEmotions7 = MusicEmotion.create(music_id: 7, emotion_id: 1)
musicEmotions8 = MusicEmotion.create(music_id: 8, emotion_id: 1)
musicEmotions9 = MusicEmotion.create(music_id: 9, emotion_id: 1)
musicEmotions10 = MusicEmotion.create(music_id: 10, emotion_id: 1)
musicEmotions11 = MusicEmotion.create(music_id: 11, emotion_id: 1)
musicEmotions12 = MusicEmotion.create(music_id: 12, emotion_id: 1)
musicEmotions13 = MusicEmotion.create(music_id: 13, emotion_id: 1)
musicEmotions14 = MusicEmotion.create(music_id: 14, emotion_id: 1)
musicEmotions15 = MusicEmotion.create(music_id: 15, emotion_id: 1)
musicEmotions16 = MusicEmotion.create(music_id: 16, emotion_id: 1)
musicEmotions17 = MusicEmotion.create(music_id: 17, emotion_id: 1)
musicEmotions18 = MusicEmotion.create(music_id: 18, emotion_id: 1)
musicEmotions19 = MusicEmotion.create(music_id: 19, emotion_id: 1)
musicEmotions20 = MusicEmotion.create(music_id: 20, emotion_id: 1)
musicEmotions21 = MusicEmotion.create(music_id: 21, emotion_id: 1)
musicEmotions22 = MusicEmotion.create(music_id: 22, emotion_id: 1)
musicEmotions23 = MusicEmotion.create(music_id: 23, emotion_id: 1)
musicEmotions24 = MusicEmotion.create(music_id: 24, emotion_id: 1)
musicEmotions25 = MusicEmotion.create(music_id: 25, emotion_id: 1)
musicEmotions26 = MusicEmotion.create(music_id: 26, emotion_id: 1)
musicEmotions27 = MusicEmotion.create(music_id: 27, emotion_id: 1)
musicEmotions28 = MusicEmotion.create(music_id: 28, emotion_id: 1)
musicEmotions29 = MusicEmotion.create(music_id: 29, emotion_id: 1)
musicEmotions30 = MusicEmotion.create(music_id: 30, emotion_id: 1)
musicEmotions31 = MusicEmotion.create(music_id: 31, emotion_id: 1)
musicEmotions32 = MusicEmotion.create(music_id: 32, emotion_id: 1)
musicEmotions33 = MusicEmotion.create(music_id: 33, emotion_id: 1)
musicEmotions34 = MusicEmotion.create(music_id: 34, emotion_id: 1)
musicEmotions35 = MusicEmotion.create(music_id: 35, emotion_id: 1)
musicEmotions36 = MusicEmotion.create(music_id: 36, emotion_id: 1)
musicEmotions37 = MusicEmotion.create(music_id: 37, emotion_id: 1)
musicEmotions38 = MusicEmotion.create(music_id: 38, emotion_id: 1)
musicEmotions39 = MusicEmotion.create(music_id: 39, emotion_id: 1)
musicEmotions40 = MusicEmotion.create(music_id: 40, emotion_id: 1)
musicEmotions41 = MusicEmotion.create(music_id: 41, emotion_id: 1)
musicEmotions42 = MusicEmotion.create(music_id: 42, emotion_id: 1)
musicEmotions43 = MusicEmotion.create(music_id: 43, emotion_id: 1)
musicEmotions44 = MusicEmotion.create(music_id: 44, emotion_id: 1)
musicEmotions45 = MusicEmotion.create(music_id: 45, emotion_id: 1)
musicEmotions46 = MusicEmotion.create(music_id: 46, emotion_id: 1)
musicEmotions47 = MusicEmotion.create(music_id: 47, emotion_id: 1)
musicEmotions48 = MusicEmotion.create(music_id: 48, emotion_id: 1)
musicEmotions49 = MusicEmotion.create(music_id: 49, emotion_id: 1)
musicEmotions50 = MusicEmotion.create(music_id: 50, emotion_id: 1)
musicEmotions51 = MusicEmotion.create(music_id: 51, emotion_id: 1)
musicEmotions52 = MusicEmotion.create(music_id: 52, emotion_id: 1)
musicEmotions53 = MusicEmotion.create(music_id: 53, emotion_id: 1)
musicEmotions54 = MusicEmotion.create(music_id: 54, emotion_id: 1)
musicEmotions55 = MusicEmotion.create(music_id: 55, emotion_id: 1)
musicEmotions56 = MusicEmotion.create(music_id: 56, emotion_id: 1)
musicEmotions57 = MusicEmotion.create(music_id: 57, emotion_id: 1)
musicEmotions58 = MusicEmotion.create(music_id: 58, emotion_id: 1)
musicEmotions59 = MusicEmotion.create(music_id: 59, emotion_id: 1)
musicEmotions60 = MusicEmotion.create(music_id: 60, emotion_id: 1)
musicEmotions61 = MusicEmotion.create(music_id: 61, emotion_id: 1)
musicEmotions62 = MusicEmotion.create(music_id: 62, emotion_id: 1)
musicEmotions63 = MusicEmotion.create(music_id: 63, emotion_id: 1)
musicEmotions64 = MusicEmotion.create(music_id: 64, emotion_id: 1)
musicEmotions65 = MusicEmotion.create(music_id: 65, emotion_id: 1)
musicEmotions66 = MusicEmotion.create(music_id: 66, emotion_id: 1)
musicEmotions67 = MusicEmotion.create(music_id: 67, emotion_id: 1)
musicEmotions68 = MusicEmotion.create(music_id: 68, emotion_id: 1)
musicEmotions69 = MusicEmotion.create(music_id: 69, emotion_id: 1)
musicEmotions70 = MusicEmotion.create(music_id: 70, emotion_id: 1)
musicEmotions71 = MusicEmotion.create(music_id: 71, emotion_id: 1)
musicEmotions72 = MusicEmotion.create(music_id: 72, emotion_id: 1)
musicEmotions73 = MusicEmotion.create(music_id: 73, emotion_id: 1)
musicEmotions74 = MusicEmotion.create(music_id: 74, emotion_id: 1)
musicEmotions75 = MusicEmotion.create(music_id: 75, emotion_id: 1)
musicEmotions76 = MusicEmotion.create(music_id: 76, emotion_id: 1)
musicEmotions77 = MusicEmotion.create(music_id: 77, emotion_id: 1)
musicEmotions78 = MusicEmotion.create(music_id: 78, emotion_id: 1)
musicEmotions79 = MusicEmotion.create(music_id: 79, emotion_id: 1)

# sad music #

music80 = Music.create(name: "With or Without You by U2" , 											file: "https://s3.amazonaws.com/emotionsproject/sad+songs/04+With+Or+Without+You.mp3")
music81 = Music.create(name: "Yesterday by The Beatles", 												file: "https://s3.amazonaws.com/emotionsproject/sad+songs/11+Yesterday.mp3")
music82 = Music.create(name: "Good Riddance (Time of Your Life) by Green Day", 	file: "https://s3.amazonaws.com/emotionsproject/sad+songs/15+Good+Riddance+(Time+of+Your+Life).mp3")
music83 = Music.create(name: "Back to Black by Amy Winehouse", 									file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Back+To+Black.mp3")
music84 = Music.create(name: "Breathe (2AM) by Anna Nalick", 										file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Breathe+(2+AM).mp3")
music85 = Music.create(name: "Brick by Ben Folds Five", 												file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Brick.mp3")
music86 = Music.create(name: "Chandelier by Sia", 															file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Chandelier.mp3")
music87 = Music.create(name: "Chicken Wire by Pernice Brothers", 								file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Chicken+Wire.mp3")
music88 = Music.create(name: "Creep by Radiohead", 															file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Creep.mp3")
music89 = Music.create(name: "Dancing by Elise", 																file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Dancing.mp3")
music90 = Music.create(name: "Friend of a Friend by Foo Fighters", 							file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Friend+of+a+Friend.mp3")
music91 = Music.create(name: "I Will Remember You by Sarah McLachlan", 					file: "https://s3.amazonaws.com/emotionsproject/sad+songs/I+Will+Remember+You.mp3")
music92 = Music.create(name: "Knockin' on Heaven's Door by Bob Dylan", 					file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Knockin%27+On+Heaven%27s+Door.mp3")
music93 = Music.create(name: "Last Kiss by Pearl Jam", 													file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Last+Kiss.mp3")
music94 = Music.create(name: "Mad World by Michael Andrews", 										file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Mad+World+(feat.+Gary+Jules).mp3")
music95 = Music.create(name: "Stole by Kelly Rowland", 													file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Stole.mp3")
music96 = Music.create(name: "The Blower's Daughter by Damien Rice", 						file: "https://s3.amazonaws.com/emotionsproject/sad+songs/The+Blower%27s+Daughter.mp3")
music97 = Music.create(name: "The Drugs Don't Work by The Verve", 							file: "https://s3.amazonaws.com/emotionsproject/sad+songs/The+Drugs+Don%27t+Work.mp3")
music98 = Music.create(name: "Thief by Our Lady Peace", 												file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Thief.mp3")
music99 = Music.create(name: "Time After Time by Cyndi Lauper", 								file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Time+After+Time.mp3")
music100 = Music.create(name: "Under the Bridge by Red Hot Chili Peppers", 			file: "https://s3.amazonaws.com/emotionsproject/sad+songs/Under+the+Bridge.mp3")

# sad musicEmotions #
musicEmotions80 = MusicEmotion.create(music_id: 80, emotion_id: 2)
musicEmotions81 = MusicEmotion.create(music_id: 81, emotion_id: 2)
musicEmotions82 = MusicEmotion.create(music_id: 82, emotion_id: 2)
musicEmotions83 = MusicEmotion.create(music_id: 83, emotion_id: 2)
musicEmotions84 = MusicEmotion.create(music_id: 84, emotion_id: 2)
musicEmotions85 = MusicEmotion.create(music_id: 85, emotion_id: 2)
musicEmotions86 = MusicEmotion.create(music_id: 86, emotion_id: 2)
musicEmotions87 = MusicEmotion.create(music_id: 87, emotion_id: 2)
musicEmotions88 = MusicEmotion.create(music_id: 88, emotion_id: 2)
musicEmotions89 = MusicEmotion.create(music_id: 89, emotion_id: 2)
musicEmotions90 = MusicEmotion.create(music_id: 90, emotion_id: 2)
musicEmotions91 = MusicEmotion.create(music_id: 91, emotion_id: 2)
musicEmotions92 = MusicEmotion.create(music_id: 92, emotion_id: 2)
musicEmotions93 = MusicEmotion.create(music_id: 93, emotion_id: 2)
musicEmotions94 = MusicEmotion.create(music_id: 94, emotion_id: 2)
musicEmotions95 = MusicEmotion.create(music_id: 95, emotion_id: 2)
musicEmotions96 = MusicEmotion.create(music_id: 96, emotion_id: 2)
musicEmotions97 = MusicEmotion.create(music_id: 97, emotion_id: 2)
musicEmotions98 = MusicEmotion.create(music_id: 98, emotion_id: 2)
musicEmotions99 = MusicEmotion.create(music_id: 99, emotion_id: 2)
musicEmotions100 = MusicEmotion.create(music_id: 100, emotion_id: 2)

# angry music #

music101 = Music.create(name: "One Step Closer by Linkin Park", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/02+One+Step+Closer.mp3")
music102 = Music.create(name: "Bodies by Drowning Pool", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Bodies.mp3")
music103 = Music.create(name: "Break Stuff by Limp Bizkit", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Break+Stuff.mp3")
music104 = Music.create(name: "Down With the Sickness by Disturbed", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Down+With+the+Sickness.mp3")
music105 = Music.create(name: "Dyers Eve by Metallica", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Dyers+Eve.mp3")
music106 = Music.create(name: "Headstrong by Trapt", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Headstrong.mp3")
music107 = Music.create(name: "I Hate Everything About You by Three Days Grace", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/I+Hate+Everything+About+You.mp3")
music108 = Music.create(name: "Killing in the Name by Rage Against the Machine", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Killing+In+the+Name.mp3")
music109 = Music.create(name: "Last Resort by Papa Roach", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Last+Resort.mp3")
music110 = Music.create(name: "Moth by Hellyeah", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Moth.mp3")
music111 = Music.create(name: "Platypus (I Hate You) by Green Day", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Platypus+(I+Hate+You).mp3")
music112 = Music.create(name: "Prison Song by System of a Down", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Prison+Song.mp3")
music113 = Music.create(name: "Stare at the Sun by Blaze Bayley", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/Stare+At+the+Sun.mp3")
music114 = Music.create(name: "The Devil in I by Slipknot", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/The+Devil+in+I.mp3")
music115 = Music.create(name: "The Way I Am by Eminem", file: "https://s3.amazonaws.com/emotionsproject/angry+songs/The+Way+I+Am.mp3")

# angry musicEmotions #

musicEmotions101 = MusicEmotion.create(music_id: 101, emotion_id: 3)
musicEmotions102 = MusicEmotion.create(music_id: 102, emotion_id: 3)
musicEmotions103 = MusicEmotion.create(music_id: 103, emotion_id: 3)
musicEmotions104 = MusicEmotion.create(music_id: 104, emotion_id: 3)
musicEmotions105 = MusicEmotion.create(music_id: 105, emotion_id: 3)
musicEmotions106 = MusicEmotion.create(music_id: 106, emotion_id: 3)
musicEmotions107 = MusicEmotion.create(music_id: 107, emotion_id: 3)
musicEmotions108 = MusicEmotion.create(music_id: 108, emotion_id: 3)
musicEmotions109 = MusicEmotion.create(music_id: 109, emotion_id: 3)
musicEmotions110 = MusicEmotion.create(music_id: 110, emotion_id: 3)
musicEmotions111 = MusicEmotion.create(music_id: 111, emotion_id: 3)
musicEmotions112 = MusicEmotion.create(music_id: 112, emotion_id: 3)
musicEmotions113 = MusicEmotion.create(music_id: 113, emotion_id: 3)
musicEmotions114 = MusicEmotion.create(music_id: 114, emotion_id: 3)
musicEmotions115 = MusicEmotion.create(music_id: 115, emotion_id: 3)

# calm music #

music116 = Music.create(name: "Swim Team", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/%27Swim+Team%27.mp3")
music117 = Music.create(name: "Brighter Than Sunshine", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/01+Brighter+Than+Sunshine.mp3")
music118 = Music.create(name: "Be a Body by Grimes", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Be+a+Body.mp3")
music119 = Music.create(name: "Can't Do Without You", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Can%27t+Do+Without+You.mp3")
music120 = Music.create(name: "Finally Moving", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Finally+Moving.mp3")
music121 = Music.create(name: "From Another World", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/From+Another+World+(feat.+Vikter+Duplaix).mp3")
music122 = Music.create(name: "Glacial", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Glacial.mp3")
music123 = Music.create(name: "Lorna", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Lorna+(feat.+Fifi+Rong).mp3")
music124 = Music.create(name: "Memories That You Call", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Memories+That+You+Call+(feat.+Monsoonsiren).mp3")
music125 = Music.create(name: "OZ", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/OZ.mp3")
music126 = Music.create(name: "Retrograde", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Retrograde.mp3")
music127 = Music.create(name: "Runaway", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Runaway.mp3")
music128 = Music.create(name: "Skinny Love", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Skinny+Love+(Sebastian+Carter+Remix).mp3")
music129 = Music.create(name: "Something About You", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Something+About+You.mp3")
music130 = Music.create(name: "Stayed", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Stayed.mp3")
music131 = Music.create(name: "Take a Moment", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Take+a+Moment+(feat.+Winter+Kills).mp3")
music132 = Music.create(name: "The Fall", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/The+Fall.mp3")
music133 = Music.create(name: "The Wilhelm Scream", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/The+Wilhelm+Scream.mp3")
music134 = Music.create(name: "Til We Ghosts", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Till+We+Ghosts.mp3")
music135 = Music.create(name: "Two Weeks", file: "https://s3.amazonaws.com/emotionsproject/calm+songs/Two+Weeks.mp3")

# calm musicEmotions #

musicEmotions116 = MusicEmotion.create(music_id: 116, emotion_id: 4)
musicEmotions117 = MusicEmotion.create(music_id: 117, emotion_id: 4)
musicEmotions118 = MusicEmotion.create(music_id: 118, emotion_id: 4)
musicEmotions119 = MusicEmotion.create(music_id: 119, emotion_id: 4)
musicEmotions120 = MusicEmotion.create(music_id: 120, emotion_id: 4)
musicEmotions121 = MusicEmotion.create(music_id: 121, emotion_id: 4)
musicEmotions122 = MusicEmotion.create(music_id: 122, emotion_id: 4)
musicEmotions123 = MusicEmotion.create(music_id: 123, emotion_id: 4)
musicEmotions124 = MusicEmotion.create(music_id: 124, emotion_id: 4)
musicEmotions125 = MusicEmotion.create(music_id: 125, emotion_id: 4)
musicEmotions126 = MusicEmotion.create(music_id: 126, emotion_id: 4)
musicEmotions127 = MusicEmotion.create(music_id: 127, emotion_id: 4)
musicEmotions128 = MusicEmotion.create(music_id: 128, emotion_id: 4)
musicEmotions129 = MusicEmotion.create(music_id: 129, emotion_id: 4)
musicEmotions130 = MusicEmotion.create(music_id: 130, emotion_id: 4)
musicEmotions131 = MusicEmotion.create(music_id: 131, emotion_id: 4)
musicEmotions132 = MusicEmotion.create(music_id: 132, emotion_id: 4)
musicEmotions133 = MusicEmotion.create(music_id: 133, emotion_id: 4)
musicEmotions134 = MusicEmotion.create(music_id: 134, emotion_id: 4)
musicEmotions135 = MusicEmotion.create(music_id: 135, emotion_id: 4)


# happy video emotions #
videoEmotion1 = VideoEmotion.create(video_id: 1, emotion_id: 1)
videoEmotion2 = VideoEmotion.create(video_id: 2, emotion_id: 1)
videoEmotion3 = VideoEmotion.create(video_id: 3, emotion_id: 1)
videoEmotion4 = VideoEmotion.create(video_id: 4, emotion_id: 1)
videoEmotion5 = VideoEmotion.create(video_id: 5, emotion_id: 1)
videoEmotion6 = VideoEmotion.create(video_id: 6, emotion_id: 1)
videoEmotion7 = VideoEmotion.create(video_id: 7, emotion_id: 1)
videoEmotion8 = VideoEmotion.create(video_id: 8, emotion_id: 1)
videoEmotion9 = VideoEmotion.create(video_id: 9, emotion_id: 1)
videoEmotion10 = VideoEmotion.create(video_id: 10, emotion_id: 1)
videoEmotion11 = VideoEmotion.create(video_id: 11, emotion_id: 1) 
videoEmotion12 = VideoEmotion.create(video_id: 12, emotion_id: 1) 
videoEmotion13 = VideoEmotion.create(video_id: 13, emotion_id: 1) 
videoEmotion14 = VideoEmotion.create(video_id: 14, emotion_id: 1) 
videoEmotion15 = VideoEmotion.create(video_id: 15, emotion_id: 1) 
videoEmotion16 = VideoEmotion.create(video_id: 16, emotion_id: 1) 
videoEmotion17 = VideoEmotion.create(video_id: 17, emotion_id: 1) 
videoEmotion18 = VideoEmotion.create(video_id: 18, emotion_id: 1) 
videoEmotion19 = VideoEmotion.create(video_id: 19, emotion_id: 1) 
videoEmotion20 = VideoEmotion.create(video_id: 20, emotion_id: 1) 
videoEmotion21 = VideoEmotion.create(video_id: 21, emotion_id: 1) 
videoEmotion22 = VideoEmotion.create(video_id: 22, emotion_id: 1) 
videoEmotion23 = VideoEmotion.create(video_id: 23, emotion_id: 1) 
videoEmotion24 = VideoEmotion.create(video_id: 24, emotion_id: 1) 
videoEmotion25 = VideoEmotion.create(video_id: 25, emotion_id: 1) 
videoEmotion26 = VideoEmotion.create(video_id: 26, emotion_id: 1) 
videoEmotion27 = VideoEmotion.create(video_id: 27, emotion_id: 1) 
videoEmotion28 = VideoEmotion.create(video_id: 28, emotion_id: 1) 
videoEmotion29 = VideoEmotion.create(video_id: 29, emotion_id: 1) 
videoEmotion30 = VideoEmotion.create(video_id: 30, emotion_id: 1) 
videoEmotion31 = VideoEmotion.create(video_id: 31, emotion_id: 1) 
videoEmotion32 = VideoEmotion.create(video_id: 32, emotion_id: 1) 
videoEmotion33 = VideoEmotion.create(video_id: 33, emotion_id: 1) 
videoEmotion34 = VideoEmotion.create(video_id: 34, emotion_id: 1) 
videoEmotion35 = VideoEmotion.create(video_id: 35, emotion_id: 1) 
videoEmotion36 = VideoEmotion.create(video_id: 36, emotion_id: 1) 

# sad video emotions #
videoEmotion37 = VideoEmotion.create(video_id: 37, emotion_id: 2)
videoEmotion38 = VideoEmotion.create(video_id: 38, emotion_id: 2)
videoEmotion39 = VideoEmotion.create(video_id: 39, emotion_id: 2)
videoEmotion40 = VideoEmotion.create(video_id: 40, emotion_id: 2)
videoEmotion41 = VideoEmotion.create(video_id: 41, emotion_id: 2)
videoEmotion42 = VideoEmotion.create(video_id: 42, emotion_id: 2)
videoEmotion43 = VideoEmotion.create(video_id: 43, emotion_id: 2)
videoEmotion44 = VideoEmotion.create(video_id: 44, emotion_id: 2)
videoEmotion45 = VideoEmotion.create(video_id: 45, emotion_id: 2)
videoEmotion46 = VideoEmotion.create(video_id: 46, emotion_id: 2)
videoEmotion47 = VideoEmotion.create(video_id: 47, emotion_id: 2)
videoEmotion48 = VideoEmotion.create(video_id: 48, emotion_id: 2)
videoEmotion49 = VideoEmotion.create(video_id: 49, emotion_id: 2)
videoEmotion50 = VideoEmotion.create(video_id: 50, emotion_id: 2) 
videoEmotion51 = VideoEmotion.create(video_id: 51, emotion_id: 2) 
videoEmotion52 = VideoEmotion.create(video_id: 52, emotion_id: 2) 
videoEmotion53 = VideoEmotion.create(video_id: 53, emotion_id: 2) 
videoEmotion54 = VideoEmotion.create(video_id: 54, emotion_id: 2) 
videoEmotion55 = VideoEmotion.create(video_id: 55, emotion_id: 2) 
videoEmotion56 = VideoEmotion.create(video_id: 56, emotion_id: 2) 
videoEmotion57 = VideoEmotion.create(video_id: 57, emotion_id: 2) 
videoEmotion58 = VideoEmotion.create(video_id: 58, emotion_id: 2) 
videoEmotion59 = VideoEmotion.create(video_id: 59, emotion_id: 2) 

# angry video emotions #
videoEmotion60 = VideoEmotion.create(video_id: 60, emotion_id: 3)
videoEmotion61 = VideoEmotion.create(video_id: 61, emotion_id: 3)
videoEmotion62 = VideoEmotion.create(video_id: 62, emotion_id: 3)
videoEmotion63 = VideoEmotion.create(video_id: 63, emotion_id: 3)
videoEmotion64 = VideoEmotion.create(video_id: 64, emotion_id: 3)
videoEmotion65 = VideoEmotion.create(video_id: 65, emotion_id: 3)
videoEmotion66 = VideoEmotion.create(video_id: 66, emotion_id: 3)
videoEmotion67 = VideoEmotion.create(video_id: 67, emotion_id: 3)
videoEmotion68 = VideoEmotion.create(video_id: 68, emotion_id: 3)
videoEmotion69 = VideoEmotion.create(video_id: 69, emotion_id: 3)
videoEmotion70 = VideoEmotion.create(video_id: 70, emotion_id: 3)
videoEmotion71 = VideoEmotion.create(video_id: 71, emotion_id: 3)
videoEmotion72 = VideoEmotion.create(video_id: 72, emotion_id: 3)
videoEmotion73 = VideoEmotion.create(video_id: 73, emotion_id: 3)
videoEmotion74 = VideoEmotion.create(video_id: 74, emotion_id: 3)
videoEmotion75 = VideoEmotion.create(video_id: 75, emotion_id: 3)
videoEmotion76 = VideoEmotion.create(video_id: 76, emotion_id: 3)
videoEmotion77 = VideoEmotion.create(video_id: 77, emotion_id: 3)
videoEmotion78 = VideoEmotion.create(video_id: 78, emotion_id: 3)
videoEmotion79 = VideoEmotion.create(video_id: 79, emotion_id: 3)

# calm video emotions #
videoEmotion80 = VideoEmotion.create(video_id: 80, emotion_id: 4) 
videoEmotion81 = VideoEmotion.create(video_id: 81, emotion_id: 4) 
videoEmotion82 = VideoEmotion.create(video_id: 82, emotion_id: 4) 
videoEmotion83 = VideoEmotion.create(video_id: 83, emotion_id: 4) 
videoEmotion84 = VideoEmotion.create(video_id: 84, emotion_id: 4) 
videoEmotion85 = VideoEmotion.create(video_id: 85, emotion_id: 4) 
videoEmotion86 = VideoEmotion.create(video_id: 86, emotion_id: 4) 
videoEmotion87 = VideoEmotion.create(video_id: 87, emotion_id: 4) 
videoEmotion88 = VideoEmotion.create(video_id: 88, emotion_id: 4) 
videoEmotion89 = VideoEmotion.create(video_id: 89, emotion_id: 4) 
videoEmotion90 = VideoEmotion.create(video_id: 90, emotion_id: 4) 
videoEmotion91 = VideoEmotion.create(video_id: 91, emotion_id: 4) 
videoEmotion92 = VideoEmotion.create(video_id: 92, emotion_id: 4) 
videoEmotion93 = VideoEmotion.create(video_id: 93, emotion_id: 4) 
videoEmotion94 = VideoEmotion.create(video_id: 94, emotion_id: 4)
videoEmotion95 = VideoEmotion.create(video_id: 95, emotion_id: 4)
videoEmotion96 = VideoEmotion.create(video_id: 96, emotion_id: 4)
videoEmotion97 = VideoEmotion.create(video_id: 97, emotion_id: 4)
videoEmotion98 = VideoEmotion.create(video_id: 98, emotion_id: 4)
videoEmotion99 = VideoEmotion.create(video_id: 99, emotion_id: 4)
videoEmotion100 = VideoEmotion.create(video_id: 100, emotion_id: 4)



# Happy Videos #
video1 = Video.create(name: 'Minions Working Out', 																		file: "www.youtube.com/embed/KLMJPKylg2Y")
video2 = Video.create(name: "Collection of happy videos", 														file: "www.youtube.com/embed/3jRiRHwL7xM")
video3 = Video.create(name: "Happy Dogs", 																						file: "www.youtube.com/embed/hGyZ2ETCTVU")
video4 = Video.create(name: "Brian Williams Rapping", 																file: "www.youtube.com/embed/-YCeIgt7hMs")
video5 = Video.create(name: "Happy at the Thrift Shop :)", 														file: "www.youtube.com/embed/QK8mJJJvaes")
video6 = Video.create(name: "BBMak Out of My Heart - happy song", 										file: "www.youtube.com/embed/I6BafxPK5pE?list=FLHgMBFypW4xk6hCTycP-C6g")
video7 = Video.create(name: "Darth kid", 																							file: "www.youtube.com/embed/R55e-uHQna0?list=FLHgMBFypW4xk6hCTycP-C6g")
video8 = Video.create(name: "Couple's song", 																				file: "www.youtube.com/embed/UFbQ3UbkYGo?list=FLHgMBFypW4xk6hCTycP-C6g")
video9 = Video.create(name: "Final Fantasy 8 happy ending with Aerosmith", 					file: "www.youtube.com/embed/vOFjLHU9in4?list=FLHgMBFypW4xk6hCTycP-C6g")
video10 = Video.create(name: "Kenny Chesney - Good Stuff",						 								file: "www.youtube.com/embed/lYQZJ9NUzYU")
video11 = Video.create(name: "lego starwars", 																				file: "www.youtube.com/embed/z0z_TU4Gw5o?list=FLHgMBFypW4xk6hCTycP-C6g")
video12 = Video.create(name: "Veteran reunited with bomb-sniffing dog", 							file: "www.youtube.com/embed/EXsH42X087Q")
video13 = Video.create(name: "Coming Home - Man Of His Word", 												file: "www.youtube.com/embed/O0sUCAzL2_Q")
video14 = Video.create(name: "Beyonce and Jay-Z Love (Roc)", 													file: "www.youtube.com/embed/a-Qn3Iaf9MI")
video15 = Video.create(name: "Beyonce - Love On Top", 																file: "www.youtube.com/embed/Ob7vObnFUJc")
video16 = Video.create(name: "Jason Derulo 'Marry Me'",	 															file: "www.youtube.com/embed/zRCsZ5a3aCM")
video17 = Video.create(name: "OneRepublic - Good Life", 															file: "www.youtube.com/embed/jZhQOvvV45w")
video18 = Video.create(name: "We Are The World 25 For Haiti",	 												file: "www.youtube.com/embed/Glny4jSciVI")
video19 = Video.create(name: "Ed Sheeran - Thinking Out Loud", 												file: "www.youtube.com/embed/lp-EO5I60KA")
video20 = Video.create(name: "Labrinth- Beneath Your Beautiful", 											file: "www.youtube.com/embed/alVMR2KEuhM")
video21 = Video.create(name: "Quicksand | Robot Chicken | Adult Swim", 								file: "www.youtube.com/embed/G_Z3lmidmrY")
video22 = Video.create(name: "For The Birds", 																				file: "www.youtube.com/watch?v=MOiyD26cJ2A")
video23 = Video.create(name: "Ormie the Pig", 																				file: "www.youtube.com/embed/EUm-vAOmV1o")
video24 = Video.create(name: "Funny kitten can't jump", 															file: "www.youtube.com/embed/fBA_lxUiwSg")
video25 = Video.create(name: "How To Pick Up Girls", 																	file: "www.youtube.com/embed/m7x57zvZLvI")
video26 = Video.create(name: "Good Hygiene Gets Girls", 															file: "www.youtube.com/embed/WZfAYWbhQP8")
video27 = Video.create(name: "Food Pic War", 																					file: "www.youtube.com/embed/zucONy9mHig")
video28 = Video.create(name: "Working Out Gets Girls", 																file: "www.youtube.com/embed/Ub_ltTBnCtE")
video29 = Video.create(name: "The Chubbchubbs", 																			file: "www.youtube.com/embed/AAm6im8bZgo")
video30 = Video.create(name: "'Apparently' This Kid is Awesome", 											file: "www.youtube.com/embed/rz5TGN7eUcM")
video31 = Video.create(name: "Ellen Introduces Kids to the Technology of Yesterday", 	file: "www.youtube.com/embed/3CMS9xnBRkc")
video32 = Video.create(name: "I Told My Kid I Ate All Their Halloween Candy", 				file: "www.youtube.com/embed/WOlpdd7y8MI")
video33 = Video.create(name: "Jim Gaffigan - Beyond the Pale - Hot Pockets", 					file: "www.youtube.com/embed/N-i9GXbptog")
video34 = Video.create(name: "Achmed the Dead Terrorist Has a Son - Jeff Dunham", 		file: "www.youtube.com/embed/IL357BrwK7c")
video35 = Video.create(name: "Double Your Money!", 																		file: "www.youtube.com/embed/w6SDqP-oxA4")
video36 = Video.create(name: "True Facts About The Aye Aye", 													file: "www.youtube.com/embed/jHs5POy8-8Y")


# sad videos #
video37 = Video.create(name: "Saddest Commercial You'll Ever See", 										file: "www.youtube.com/embed/EEYm2zA7h_k")
video38 = Video.create(name: 'Just a very Sad Story', 																	file: "www.youtube.com/embed/jXmluLg2XP0")
video39 = Video.create(name: "Bullying", 																							file: "www.youtube.com/embed/q4syd4vKFPE")
video40 = Video.create(name: "Father and Son", 																				file: "www.youtube.com/embed/1BZmuz88KEY")
video41 = Video.create(name: "Story about suicide",	 																	file: "www.youtube.com/embed/aMqFflLJN38")
video42 = Video.create(name: "Man loses his life and love", 													file: "www.youtube.com/embed/_Ef8ZHgxxK0")
video43 = Video.create(name: "Raymond Lam wonders about someone else's life", 				file: "www.youtube.com/embed/cBNXAxjabw0")
video44 = Video.create(name: "Five for Fighting's Augie Nieto", 											file: "www.youtube.com/embed/dJsm31yw4Uo?list=FLHgMBFypW4xk6hCTycP-C6g")
video45 = Video.create(name: "Sam and Annie - Life on Mars", 													file: "www.youtube.com/embed/xBm-WWY87r8")
video46 = Video.create(name: "Ray Lam If The Time Ever Arrives", 											file: "www.youtube.com/embed/Fawpke7fJDw")
video47 = Video.create(name: "Father who is blind", 																	file: "www.youtube.com/embed/SV6Sw9CNWek")
video48 = Video.create(name: "Bruno Mars Talking to the Moon", 												file: "www.youtube.com/embed/K59Tmrs9YD0")
video49 = Video.create(name: "Lonestar - I'm Already There", 													file: "www.youtube.com/embed/1jm5gfuT9Z4")
video50 = Video.create(name: "Johnny Cash - Hurt", 																		file: "www.youtube.com/embed/3aF9AJm0RFc")
video51 = Video.create(name: "Kiwi!", 																								file: "www.youtube.com/embed/sdUUx5FdySs")
video52 = Video.create(name: "Strangers, again", 																			file: "www.youtube.com/embed/tSdELZxEnHY")
video53 = Video.create(name: "The Places We Should Have Gone", 												file: "www.youtube.com/embed/9xg1-dzWg3A")
video54 = Video.create(name: "Tamia - Officially Missing You", 												file: "www.youtube.com/embed/HeK1zQFJtXE")
video55 = Video.create(name: "Passenger - Let Her Go", 																file: "www.youtube.com/embed/RBumgq5yVrA")
video56 = Video.create(name: "Sad Cat Diary", 																				file: "www.youtube.com/embed/PKffm2uI4dk")
video57 = Video.create(name: "Henri - Politique", 																		file: "www.youtube.com/embed/CvQPzmoKuBk")
video58 = Video.create(name: "Katy Perry - The One That Got Away", 										file: "www.youtube.com/embed/Ahha3Cqe_fk")
video59 = Video.create(name: "Katy Perry - Thinking Of You", 													file: "www.youtube.com/embed/wdGZBRAwW74")

# angry videos #
video60 = Video.create(name: "Lady Gaga - Telephone", 																file: "www.youtube.com/embed/EVBsypHzF3U")
video61 = Video.create(name: "Lady Gaga - Paparazzi", 																file: "www.youtube.com/embed/d2smz_1L2_0")
video62 = Video.create(name: "Beyonce - Why Don't You Love Me", 											file: "www.youtube.com/embed/QczgvUDskk0")
video63 = Video.create(name: "Beyonce - Ring The Alarm", 															file: "www.youtube.com/embed/eY_mrU8MPfI")
video64 = Video.create(name: "Eminem - Cleaning Out My Closet", 											file: "www.youtube.com/embed/RQ9_TKayu9s")
video65 = Video.create(name: "Metallica - Sad But True", 															file: "www.youtube.com/embed/A8MO7fkZc5o")
video66 = Video.create(name: "Megadeth - Train Of Consequences", 											file: "www.youtube.com/embed/-G38VlmOib8")
video67 = Video.create(name: "Beastie Boys - Sabotage", 															file: "www.youtube.com/embed/z5rRZdiu1UE")
video68 = Video.create(name: "Metallica - Ain't my Bitch", 														file: "www.youtube.com/embed/gl0vp7DvWG8")
video69 = Video.create(name: "Guns N' Roses-Back off Bitch", 													file: "www.youtube.com/embed/SNcViNwac0I")
video70 = Video.create(name: "Clash - I Fought The Law (live)", 											file: "www.youtube.com/embed/FKIzjF25sP8")
video71 = Video.create(name: "Onyx - Slam", 																					file: "www.youtube.com/embed/7ADgCeYJMN4")
video72 = Video.create(name: "Method Man - Judgement Day", 														file: "www.youtube.com/embed/5F4kTIFsg_M")
video73 = Video.create(name: "Chumbawamba - Tubthumping", 														file: "www.youtube.com/embed/2H5uWRjFsGc")
video74 = Video.create(name: "The Avengers - Hulk Smash", 														file: "www.youtube.com/embed/-m6UKS1L0YQ")
video75 = Video.create(name: "Angry Mob", 																						file: "www.youtube.com/embed/D74Xs1VuYAE")
video76 = Video.create(name: "Tiffany attacks Piper", 																file: "www.youtube.com/embed/pd675xMUhmQ")
video77 = Video.create(name: "Game of Thrones angry mob", 														file: "www.youtube.com/watch?v=7RO7uISJ7xM&list=PL6TWX8Q2VbYlwZIDOHLJ-cclVIXMM0r1m&index=18")
video78 = Video.create(name: "Game of Thrones epic Tyrion scene", 										file: "www.youtube.com/watch?v=hVvpRpTiUlo&index=19&list=PL6TWX8Q2VbYlwZIDOHLJ-cclVIXMM0r1m")
video79 = Video.create(name: "Game Of Thrones The Red Viper vs The Mountain", 				file: "www.youtube.com/watch?v=qyOw7ScY4F4&index=20&list=PL6TWX8Q2VbYlwZIDOHLJ-cclVIXMM0r1m")

# calm videos #
video80 = Video.create(name: "Black Crowes - She Talks to Angels", 										file: "www.youtube.com/embed/8_5U0M9ErGA?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video81 = Video.create(name: "Four Hours of Relaxing Music", 													file: "www.youtube.com/embed/mMIGQ1L0W4w?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video82 = Video.create(name: "The Best Beethoven", 																		file: "www.youtube.com/embed/8ptfyhBjXj8?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video83 = Video.create(name: "Best of Mozart", 																				file: "www.youtube.com/embed/l153UtpCKEI?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video84 = Video.create(name: "Four Seasons - Vivaldi", 																file: "www.youtube.com/embed/GRxofEmo3HA?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video85 = Video.create(name: "Gorgeous Gregorian Chant", 															file: "www.youtube.com/embed/3ElL8hdQD_4?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video86 = Video.create(name: "Gregorian - Find My Way Home", 													file: "www.youtube.com/embed/dKpX-o-AMaY?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video87 = Video.create(name: "Gregorian - Chasing Cars - Snow Patrol", 								file: "www.youtube.com/embed/ipouElsybfs?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video88 = Video.create(name: "Relaxing Music", 																				file: "www.youtube.com/embed/c2-e7Z1LEL8?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video89 = Video.create(name: "Playlist of Relaxing Soft Piano", 											file: "www.youtube.com/embed/vCYk9CRx0g8?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video90 = Video.create(name: "Traditional Chinese Music", 														file: "www.youtube.com/embed/FKCD8O1fark?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video91 = Video.create(name: "BRAVEHEART Instrumental", 															file: "www.youtube.com/embed/pNuZIZOya78?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video92 = Video.create(name: "Best Romantic Relaxing music", 													file: "www.youtube.com/embed/6Lq_0P39iLg?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video93 = Video.create(name: "OMC - How Bizzare", 																		file: "www.youtube.com/embed/oGUMsxVt4YU?list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI")
video94 = Video.create(name: "Yanni", 																								file: "www.youtube.com/embed/WaoaZiTPiik")
video95 = Video.create(name: "Enya - Only Time", 																			file: "www.youtube.com/embed/7wfYIMyS_dI")
video96 = Video.create(name: "Jim Brickman - The Promise", 														file: "www.youtube.com/watch?v=S0qScj6mEQs&list=PL6TWX8Q2VbYm_wbFQYtO0AMDTaIZn49LI&index=16")
video97 = Video.create(name: "OMAR AKRAM - Dancing with the wind", 										file: "www.youtube.com/embed/3r99DIRPE2s")
video98 = Video.create(name: "OMAR AKRAM - Secret Journey", 													file: "www.youtube.com/embed/5tTxRNHGY2E")
video99 = Video.create(name: "OMAR AKRAM - Whispers in the moonlight", 								file: "www.youtube.com/embed/MiawFKfhT8Q")
video100 = Video.create(name: "William Joseph - Sweet Remembrance Of You", 						file: "www.youtube.com/embed/xh1z8LKrQdg")
